import { createSlice } from "@reduxjs/toolkit";

// cartSlice = {

//   name: "cart",

//   reducer: function(state, action) {
//       // Combined reducer generated by Redux Toolkit
//   },

//   actions: {

//       addItem: function(payload) {
//           return {
//               type: "cart/addItem",
//               payload
//           };
//       },

//       removeItem: function(payload) {
//           return {
//               type: "cart/removeItem",
//               payload
//           };
//       }

//   }

// }

const cartSlice = createSlice({
    name: "cart",
    initialState: {
        items: [],
    },
    reducers: {
        addToCart: (state, action) => {
            const product = action.payload;
            const cartItem = state.items.find(
                (item) => item.id === product.id
            );
            if(cartItem) {
                cartItem.quantity += 1;
            }
            else{
                state.items.push({...product, quantity: 1});
            }
        },
        increaseQuantity: (state, action) => {
            const productId = action.payload;
            const cartItem =state.items.find(
                (item) => item.id === productId
            );
            if(cartItem) {
                cartItem.quantity += 1;
            }
        },
        decreaseQuantity: (state, action) => {
            const productId = action.payload;
            const cartItem = state.items.find((item) => item.id === productId);
            if(cartItem) {
                if(cartItem.quantity > 1)
                    cartItem.quantity -= 1;
                else{
                    state.items = state.items.filter((item) => item.id !== productId);
                }
            }
        },
        removeItem: (state, action) => {
            const productId = action.payload;
            state.items = state.items.filter((item) => item.id !== productId);
        },
        clearCart: (state) => {
            state.items = [];
        }
    },
});

export const {addToCart, increaseQuantity, decreaseQuantity, removeItem, clearCart} = cartSlice.actions;

export default cartSlice.reducer;